### ISSUE TITLE
Gardener should avoid building garden too close to map edge

### ISSUE THREAD

**Issue by Lukx19** [hrnr/battlecode-2017-blueteam#12]
#11 On the map Alone can be observed that gardener builds his garden too close to map edge. This causes him  to loose bullet points and sometimes the gardener is not able to spawn any units.

**Comment by exxaxxxx** [comment]
I have actually tried to edit gardener in my new branch, that after 100 unsuccesful round to just build garden no matter where he is and it worked surprisingly good, it acted in similiar way like the team that crushed us economically. I need more testing to prove that this is the right way.
